matrix:
  include:
    - os: linux
      sudo: true
      dist: trusty
      language: c
      addons:
        apt:
          packages:
            - make
            - python
            - libpython-dev
            - libffi-dev
            - python3
            - python3-pip
      # before_install:
      #   -
      install:
        - 'cd env'
        - './ubuntu-14.04-setup.sh'
        - 'cd ..'
      script:
        # Setup the build environment
        - 'source env/enter_env.sh'
        # Run the test builds
        - 'env/test_build.sh'
      # after_success:
      #   - echo "After_Success"

# vim:sw=2:
